name: Deploy Terraform to GCP

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_PROJECT: ${{ secrets.PROJECT_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SECRET_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Terraform Init
        working-directory: ../
        run: terraform init

      - name: Terraform Plan
        working-directory: ../
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ../
        run: terraform apply -auto-approve tfplan

